# $FreeBSD$

PORTNAME=	ffnvcodec
DISTVERSIONPREFIX=	n
DISTVERSION=	11.0.10.0
CATEGORIES=	multimedia

MAINTAINER=	multimedia@FreeBSD.org
COMMENT=	FFmpeg headers to interface with NVIDIA video encoder (NVENC)

LICENSE=	MIT

USES=		gmake pkgconfig

USE_GITHUB=	yes
GH_ACCOUNT=	FFmpeg
GH_PROJECT=	nv-codec-headers

.include <bsd.port.mk>
